config/routes.rb
Rails.application.routes.draw do
  get '/question', to: 'pages#question', as: :question_page
  post '/question', to: 'pages#question', as: :question_page_post
  get '/answer', to: 'pages#answer', as: :answer_page
  post '/answer', to: 'pages#answer', as: :answer_page_post
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def question
    # raise
    # @question = params[:question]
  end

  def answer
    # raise
    @question = params[:question]
    @answer = "Answer!!"
    if @question == "I'm going to work!"
      @answer = "Great!"
    elsif @question.end_with? '?'
      @answer = "Silly question! Get dressed and go to work!"
    else
      @answer = "I don't care!"
    # raise
    end
    @answer
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/answer.html.erb
<!-- <h1>Pages#answer</h1>
<p>Find me in app/views/pages/answer.html.erb</p> -->
<h1>Stupid Coach</h1>

<h2>Your answer</h2>
<p><%= @question %></p>
<h2>Your coach's answer</h2>
<p><%= @answer %></p>

<%= link_to 'ask a new question', question_page_path %>

app/views/pages/question.html.erb
<!-- <h1>Pages#question</h1>
<p>Find me in app/views/pages/question.html.erb</p> -->
<h1>Stupid Coach</h1>

<form action="/answer" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="question" placeholder="What's the question?">
  <!-- <input type="text" name="address" placeholder="Address"> -->
  <input type="submit">
</form>

<h2><%= @question %></h2>